name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build Process
        run: |
          # 1. تحديث نسخة المكتبة المتعارضة لضمان التوافق مع الإصدار الحديث
          flutter pub add intl:^0.20.2
          flutter pub get
          
          # 2. إنشاء مجلدات وهمية لمنع فشل البناء بسبب ملفات الـ Assets المفقودة في جيت هب
          mkdir -p assets/images assets/icons assets/fonts
          touch assets/fonts/Inter-Regular.ttf
          touch assets/fonts/Inter-Medium.ttf
          touch assets/fonts/Inter-SemiBold.ttf
          touch assets/fonts/Inter-Bold.ttf
          
          # 3. تهيئة ملفات الأندرويد لضمان توافق الـ Gradle
          flutter create . --platforms android
          
          # 4. تنظيف المشروع وبناء الـ APK النهائي
          flutter clean
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SwiftBolt-APK
          path: build/app/outputs/flutter-apk/app-release.apk
